#!/usr/bin/env sh

#xfce terminal
super + Return
	eval $TERMINAL
	

#sublime
super + ctrl + w
	eval $EDITOR
#Pycharm
super + ctrl + p
	code
#Spotify
super + ctrl + s
	spotify
#Foxit Reader
super + ctrl + r 
	eval $READER
#Browser
super + ctrl + b
	eval $BROWSER
#Email
super + ctrl + e
	eval $EMAIL
# Thunar File Manager 
super + ctrl + t
        eval $FILEMANAGER

# Change the keyboard layout
super + F3
	setxkbmap it   
super + F5
        setxkbmap se   


# Audio
alt + {Down, Up}
    pactl -- set-sink-volume @DEFAULT_SINK@ {-,+}10%
#    amixer -q set Master 1%{-,+}
#	amixer -q set PCM 1%{-,+} #decrease/raise volume
alt + m
    pactl set-sink-mute @DEFAULT_SINK@ toggle	
#	amixer -D pulse set Master 1+ toggle #mute/unmute

alt + super + m
#	amixer -q set Master 100% #max volume
	pactl set-sink mute @DEFAULT_SINK@ +140%
#Brightness
#alt + ctrl + Up
#	xbacklight -inc 10 #raise brightness
#alt + ctrl + Down
#	xbacklight -dec 10 #decrease brightness
 

#shutdown
ctrl + F1
	shutdown -h now
#spotify 

	#next
ctrl + F11
	dbus-send --print-reply  --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
	#previous
ctrl + F9
	dbus-send --print-reply  --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
	#stop
ctrl + F10
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

